# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.cache/wt [current_project]
set_property parent.project_path C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/scene_cross.v
read_verilog -library xil_defaultlib {
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/Periodchange.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/bg_layer_ip.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/car_rect_rot_ip.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/cfg_uart_simple.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/font.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/key_filter.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/mode_label.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/ped_sensor.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/scene_anim.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/sincos90_q88.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/tick_anim.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/traffic_adapt2.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/traffic_count_map.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/traffic_ctrl_adaptive.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/uart_rt.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/vga_ctrl.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/vga_pic.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/new/word_renderer.v
  C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/imports/new/vga_colorbar.v
}
read_ip -quiet C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/constrs_1/imports/new/vga.xdc
set_property used_in_implementation false [get_files C:/Users/Conor/Desktop/zynq_fpga/version2/vgatest/vgatest.srcs/constrs_1/imports/new/vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vga_colorbar -part xc7z020clg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_colorbar.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_colorbar_utilization_synth.rpt -pb vga_colorbar_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
